<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/05 00:51:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=foo_bar_db',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
