<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/06/02 01:34:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/tmp/sf_sandbox/data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
