<?php

/**
 * BaseAddresses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $phone
 * @property object $description
 * 
 * @method string    getFirstName()   Returns the current record's "first_name" value
 * @method string    getLastName()    Returns the current record's "last_name" value
 * @method string    getEmail()       Returns the current record's "email" value
 * @method integer   getPhone()       Returns the current record's "phone" value
 * @method object    getDescription() Returns the current record's "description" value
 * @method Addresses setFirstName()   Sets the current record's "first_name" value
 * @method Addresses setLastName()    Sets the current record's "last_name" value
 * @method Addresses setEmail()       Sets the current record's "email" value
 * @method Addresses setPhone()       Sets the current record's "phone" value
 * @method Addresses setDescription() Sets the current record's "description" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddresses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('addresses');
        $this->hasColumn('first_name', 'string', 40, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('last_name', 'string', 40, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('email', 'string', 40, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('phone', 'integer', 40, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('description', 'object', null, array(
             'type' => 'object',
             'notnull' => false,
             ));

        $this->option('type', 'MYISAM');
        $this->option('collate', 'utf8_general_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'notnull' => false,
             ),
             'updated' => 
             array(
              'name' => 'updated',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
              'notnull' => false,
             ),
             ));
        $this->actAs($timestampable0);
    }
}