<?php

/**
 * AddressesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddressesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AddressesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Addresses');
    }
}